import { readFileSync, writeFileSync } from 'node:fs';

// The .d.ts the web client feeds to Monaco is not valid standalone TypeScript.
// Monaco tolerates the breakage; tsc does not. This rewrites it into something
// that type-checks locally, without touching the pristine copy.
const SOURCE = 'types/classicuo-scripting.d.ts';
const OUTPUT = 'types/classicuo.d.ts';

const raw = readFileSync(SOURCE, 'utf8');
const split = raw.indexOf('declare module globalThis {');

if (split === -1) {
  throw new Error('could not find the globalThis block - did the client typings change?');
}

let modules = raw.slice(0, split);
const globals = raw.slice(split);

// 1. The generator emitted `enums` as a bare identifier where a module name belongs
modules = modules.replaceAll('declare module enums {', 'declare module "enums" {');
modules = modules.replaceAll(' from enums;', ' from "enums";');

// 2. ...which leaves a block of the enums module re-exporting itself
modules = modules.replaceAll('    export * from "enums";\n', '');

// 3. Three types are referenced but never shipped. They are equally broken in the
//    real IDE; `any` at least lets the rest of the file resolve.
modules = modules.replace(
  'declare module "index" {\n    export * from "WorldMap";\n}',
  `declare module "index" {
    export * from "WorldMap";
    /** Not shipped in the client's typings - real shape unknown */
    export type TargetInfo = any;
    /** Not shipped in the client's typings - real shape unknown */
    export type MenuPopupData = any;
}`,
);

modules += `declare module "ItemSchema" {
    /** Not shipped in the client's typings - real shape unknown */
    export type VendorItem = any;
}
`;

// 4. `declare module globalThis` collides with the built-in. Re-emit its members as
//    plain ambient declarations, using import() types so the file stays a script.
const namespaceBody = globals.match(/export namespace globalThis \{\n([\s\S]*?)\n {4}\}/);

if (!namespaceBody) {
  throw new Error('could not parse the globalThis namespace body');
}

const members = namespaceBody[1]
  .split('\n')
  .map((line) => (line.startsWith('        ') ? line.slice(8) : line))
  .join('\n')
  .replace(/^(const|function) /gm, 'declare $1 ');

// Classes and enums are re-exported into global scope at the end of the block
const reExports = [...globals.matchAll(/^ {4}export \{ (\w+) \} from (?:"([^"]+)"|(\w+));$/gm)];

const aliases = reExports
  .map(([, name, quoted, bare]) => {
    const from = quoted ?? bare;
    return `type ${name} = import("${from}").${name};\ndeclare const ${name}: typeof import("${from}").${name};`;
  })
  .join('\n');

const typeOnly = [...globals.matchAll(/^ {4}export type \{ (\w+) \} from "([^"]+)";$/gm)]
  .map(([, name, from]) => `type ${name} = import("${from}").${name};`)
  .join('\n');

const header = `// GENERATED by scripts/patch-types.mjs - edit that, not this.
// Source: types/classicuo-scripting.d.ts, extracted from play.classicuo.org.

`;

writeFileSync(OUTPUT, `${header}${modules}\n${typeOnly}\n${aliases}\n\n${members}\n`);
console.log(`wrote ${OUTPUT}`);
